export const GET_ALL_CUSTOMER_LOADING = "GET_ALL_CUSTOMER_LOADING"
export const GET_ALL_CUSTOMER_SUCCESS = "GET_ALL_CUSTOMER_SUCCESS"
export const GET_ALL_CUSTOMER_ERROR = "GET_ALL_CUSTOMER_ERROR"





// get delte the customer 

export const GET_CUSTOMER_DELETE_LOADING = 'GET_CUSTOMER_DELETE_LOADING';
export const GET_CUSTOMER_DELETE_SUCCESS = 'GET_CUSTOMER_DELETE_SUCCESS';
export const GET_CUSTOMER_DELETE_ERROR = 'GET_CUSTOMER_DELETE_ERROR';




// get customer update
export const GET_CUSTOMER_UPDATE_LOADING = 'GET_CUSTOMER_UPDATE_LOADING';
export const GET_CUSTOMER_UPDATE_SUCCESS = 'GET_CUSTOMER_UPDATE_SUCCESS';
export const GET_CUSTOMER_UPDATE_ERROR = 'GET_CUSTOMER_UPDATE_ERROR' ;



